#####
POST http://localhost:3000/api/student HTTP/1.1
content-type: application/json

{
  "name": "Sample Student",
  "email": "sample@student.com"
}

#####
POST http://localhost:3000/api/student HTTP/1.1
content-type: application/json

{
  "name": "Sample Student",
  "email": "sample@student.com",
  "$connect": {
    "classrooms": [2]
  }
}

#####
GET http://localhost:3000/api/student HTTP/1.1
content-type: application/json

###### 
@target = 2

GET http://localhost:3000/api/student/{{target}} HTTP/1.1
content-type: application/json

#####
DELETE http://localhost:3000/api/student/{{target}} HTTP/1.1
content-type: application/json

#####
PUT http://localhost:3000/api/student/{{target}} HTTP/1.1
content-type: application/json

{
  "name": "Updated Student"
}

#####
PUT http://localhost:3000/api/student/{{target}} HTTP/1.1
content-type: application/json

{
  "name": "Updated Student",
  "$connect": {
    "classrooms": [2]
  },
  "$disconnect": {
    "classrooms": [1, 3]
  }
}